### PR TITLE
Added support for the terminology service client to use token authentication.

### PR DESCRIPTION
**Pull request by michealharrington**
Our Terminology Service doesn't support basic authentication (username / password) and requires OAuth 2 tokens.

This modification allows for the client to be passed a single parameter which is treated as the Authorization header.

Example usage
```python
    terminology_client = terminology_service_client.TerminologyServiceClient(
        {
            f"https://test-terminlogy.com/api/fhir/R4/ValueSet/$expand": (
                f"Bearer {access_token}"
            )
        }
    )
```

### CODE REVIEW

**Comment by michealharrington** [comment]
Would love to get this merged so I can remove my fork and use the official version. Anything I can do?

**Comment by rbrush** [comment]
Hi Michael, apologies for the very delayed response. 

I think the essence of this change is fine, but since this effectively changes the `auth_per_terminology_server` structure to contain an option of two different types, we should reflect that in the TerminologyServiceClient constructor by updating the pytype type signature and documentation on the class itself.

Are you able to add an update there as well? If so we can merge this PR in.

**Comment by michealharrington** [comment]
I'm by no means a python expert, do you happen to know why this change failed the tests?

**Comment by rbrush** [comment]
I don't think these are related. Some of the tests pull FHIR structure definitions from HL7-hosted repos, so it looks like they are temporarily unavailable. We'll re-run the tests a bit later to see that resolves the issue, at which point this should merge fine.

**Comment by rbrush** [comment]
Alright, this went through cleanly after the HL7 repos came back online, so I think we're good here.

**Pull request merged**
